language: 
        - gcc
        - clang

script:
        - cmake .
        - make
addons:
        apt:
                packages:
                        - cmake
                        - cmake-data

